version: '3.0'
services:
  client:
    image: node:19.2.0-alpine
    container_name: client
    build:
      context: .
      dockerfile: Client.Dockerfile
    restart: unless-stopped
    hostname: client 
    ports:
      - 3000:${CLIENT_PORT}
    depends_on:
      - panel
      - nginx
    command: npm run start
    networks:
      - nesjs-network
    network_mode: bridge
    volumes:
      - .:/client
      - .:/client/node_modules