version: '3.0'
services:
  client:
    image: node:19.2.0-alpine
    container_name: client
    extra_hosts:
    - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Client.Dockerfile
    restart: unless-stopped
    hostname: client 
    ports:
      - 3000:${CLIENT_PORT}
    command: npm run start
    network_mode: bridge
    volumes:
      - .:/client
      - .:/client/node_modules